# Generated by Django 3.0.5 on 2020-06-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='email_id',
            new_name='user',
        ),
    ]
