# Generated by Django 3.0.5 on 2020-06-13 09:06

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('users', '0002_auto_20200611_1452'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social',
            new_name='SocialLoginDetails',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='UserDetails',
        ),
    ]
