# Generated by Django 3.0.5 on 2020-06-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200614_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallogindetails',
            name='meta',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
