# Generated by Django 3.0.5 on 2020-06-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200614_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallogindetails',
            name='meta',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
